done API Hacker News
Useit14/web_bee_HackerNews pull request #1
Opened 2022-08-21 07:32 UTC by Useit14

2022-08-21 09:38 UTC, Useit14 commented
https://codesandbox.io/s/festive-borg-bbb242
https://bbb242.csb.app/

2022-08-22 11:36 UTC, crutch12 commented
отдал @stilwuc

2022-08-23 10:44 UTC, Stilwuc requested changes
Неплохо неплохо 👍 
Но парочку вещей поправить надо)

2022-08-23 10:44 UTC, Stilwuc commented on src/App.css
> +.App {
Не юзаешь эти стили из CRA, можно выпилить чтобы не мешались)

2022-08-23 10:44 UTC, Stilwuc commented on src/App.tsx
> +            <Route path="/home" element={<Home />} />
Интересно, а зачем тебе два разных роута ведущих на один и тот же компонент?)
Легче сделать один роут и не парится

2022-08-23 10:44 UTC, Stilwuc commented on src/App.tsx
> +    setInterval(() => {
`clearInterval` хочется, даже если здесь конкретно память от этого не потечет, все же это хорошая привычка: создал интервал почисти его (в идеале такое даже с setTimeout делать если он долгий)

2022-08-23 10:44 UTC, Stilwuc commented on src/App.tsx
> +    getFeedItems().then((e) => setData(e));
Переменные/параметры в одну букву не самая лучшая тема, иногда конечно можно такое забивать как например в `catch(e)` но я бы даже тут не советовал, а то вне контекста эта буква e ничего тебе не говорит.
В твоем случае подойдет `feedItems  | items | response | data`

2022-08-23 10:44 UTC, Stilwuc commented on src/types/types.tsx
> +export interface IComment {
Codestyle коммент:
Лучше не называть интерфейс с префиксом `I` больше c тема, и ухудшает читаемость, для нас важно что это просто тип, а это обозначается кейсом
Тем более что где то у тебя с префиксом а где то нет (`FeedItem`)

2022-08-23 10:44 UTC, Stilwuc commented on src/components/Comments.tsx
> +    getItem(window.location.pathname).then((e) => setData(e));
Лучше не юзать `window.location` а юзать `useLocation` из `react-router-dom`.
Так у тебя не будет потенциальных проблем с ssr, да и получишь более точный path (если делал какие нибудь `baseUrl`)

2022-08-23 10:44 UTC, Stilwuc commented on src/components/Comments.tsx
> +    navigate(-1);
В текущей ситуации лучше хардкодить на конкретный роут (`navigate('/')`)
А то если я открою в новой вкладке новость то у меня истории вкладки не будет и этот -1 не сработает

2022-08-23 10:44 UTC, Stilwuc commented on src/components/Comments.tsx
> +    setInterval(() => {
Вот тут точно нужен clearInterval.
Так как ты с этой страницы можешь на другую уйти, и очистить эту джобу надо а то она будет в фоне выполнятся

2022-08-23 10:44 UTC, Stilwuc commented on src/hooks/getItem.tsx
> +  const hrefArr = loc.split("/");
Лучше передавать сюда чисто id
А вычислять его снаружи с помощью хука `useParams`

2022-08-23 10:44 UTC, Stilwuc commented on src/App.tsx
> +    getFeedItems().then((e) => setData(e));
А поч кстати этот запрос в глобал `App` компоненте тригерится, а не на конкретной странице всех новостей?
Просто если я захожу на одну новость мне же данные по всем новостям не нужны

2022-08-23 10:44 UTC, Stilwuc commented on src/components/Comments.tsx
> +            <Comment>
отступ бы какой нибудь между комментами, а то слипаются авторы с другими комментами
 
![image](https://user-images.githubusercontent.com/44724024/186135718-a6a0b093-9115-4975-b334-d08deb3a9a24.png)

2022-08-23 10:44 UTC, Stilwuc commented on src/hooks/getFeedItems.tsx
> +  for (let i = 1; arr.length < 100; i++) {
Получилось 120 итемов, а нужно 100
![image](https://user-images.githubusercontent.com/44724024/186136329-f333ff28-5f37-4108-ac6f-f05855c0d07d.png)

2022-08-23 10:44 UTC, Stilwuc commented on src/components/NewsItem.tsx
> +  const TitleNew = styled.div`
styled за компонентом надо объявлять
А то будешь создавать его каждый раз на ререндер
![image](https://user-images.githubusercontent.com/44724024/186136825-3b5eab31-aca2-4d17-b9bb-ab21682ecbc6.png)

2022-08-23 10:44 UTC, Stilwuc commented on src/components/NewsItems.tsx
> +            key={item.index}
Когда есть уникальный идентификатор в объекте(в твоем случае `item.id`) лучше его использовать как `key`.
Будет кошерная оптимизация, а то при ресортинге (`refetch` в твоем случае с новой новостью) сейчас он оч неоптимизированно будет работать по `index`

2022-08-23 10:44 UTC, Stilwuc commented on src/functions/getContent.ts
> +export const getContent: (code: string) => string = (code: string) => {
немного лишнего дубля типизации, можно сделать короче
```suggestion
export const getContent = (code: string): string => {
```

2022-08-23 10:44 UTC, Stilwuc commented on src/functions/getContent.ts
> +  tag.innerHTML = code;
Не самое хорошее решение, так как часть верстки теряется, например те же ссылки теперь отображаются как обычный текст
![image](https://user-images.githubusercontent.com/44724024/186138017-e5b1a669-158d-4229-bb03-cde2166ff0b6.png)
Вот origin
![image](https://user-images.githubusercontent.com/44724024/186138062-4da8387a-f085-4547-a6aa-5b1cc82d703e.png)

Вот более правильное в данном случее (относительно норм, но в enterprise надо еще обезопасится фильтрацией опасных элементов)
https://ru.reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml

2022-08-23 10:44 UTC, Stilwuc commented on src/components/Comments.tsx
> +  const getInnerComments: (comments: Item, level: number) => React.ReactNode = (
У тебя вот эта функция +- повторяет нижний рендер компонента.
Попробуй избавится от дублирования

2022-08-23 10:44 UTC, Stilwuc commented on src/components/Comments.tsx
> +                {comment?.[item.id] === true ? (
```
{comment?.[item.id] && getInnerComments(item, item.level + 1)}
```

2022-08-25 11:16 UTC, Stilwuc requested changes
Еще парочку)

2022-08-25 11:16 UTC, Stilwuc commented on src/App.tsx
> +  const [data, setData] = useState<FeedItem[]>([]);
Эту чтуку уже можно выкинуть чисто в компонент `<Home />`, так как этот стейт все равно только там юзается

2022-08-25 11:16 UTC, Stilwuc commented on package.json
> +    "@testing-library/jest-dom": "^5.16.5",
Вижу у тебя блок devDeps поэтому придерусь и тут)
Все `@types` пакеты в `devDependencies` должны лежать, так как все что связано с ts обычно это нужно только при разработке

2022-08-25 11:16 UTC, Stilwuc commented on src/ContextData.tsx
> +export const ContextComments = React.createContext<ContextComment>({
По факту тебе оба эти контекста не нужны, так как юзаешь все один раз в одном компоненте.
Но так как в ТЗ было обязательно заюзать state management то ок, но лучше один только оставь contenxt Comments я думаю подет)

2022-08-25 11:16 UTC, Stilwuc commented on src/ContextData.tsx
> +  setComment: function (par) {
Аргумент не типизирован

2022-08-25 11:16 UTC, Stilwuc commented on src/components/Comments.tsx
> +    clearInterval(idInterval);
Чистить надо не тут а на unmount
Обычно это та функция которая возвращается из useEffect
https://dev.to/robmarshall/how-to-use-componentwillunmount-with-functional-components-in-react-2a5g

2022-08-25 11:16 UTC, Stilwuc commented on src/types/types.tsx
> +export interface ICompare {
Все еще есть `I`

2022-08-25 14:11 UTC, Stilwuc approved these changes
Шик, мержи

2022-08-25 14:20 UTC, merged